---

- hosts: mail-host
  gather_facts: false
  tasks:

    - name: "Include additional variables / inventory content"
      include_vars:
        file: "{{ item }}"
      with_items: "{{ email_template | fileglob }}"

- name: Notify users
  import_playbook: "../../requirements_roles/infra-ansible/playbooks/notifications/email-notify-users.yml"
  vars:
    users: "{{ identities.users }}"
