---

- hosts: localhost
  name: Remove participants from queue
  tasks:

    - name: "Clone git repository"
      include_role:
        name: "../../requirements_roles/infra-ansible/roles/scm/git"
      vars:
        action: pull
      when:
        - repository is defined

    - name: Ensure list of email addresses is empty
      set_fact:
        emails_to_match: []

    - name: Create a list of email addresses to search the queue
      set_fact:
        emails_to_match: "{{ (emails_to_match | default([])) + [ user.email ] }}"
      loop:
        "{{ lodestar_identities_remove.users | flatten(levels=1) }}"
      loop_control:
        index_var: index
        loop_var: user

    - name: "Remove processed files from job queue"
      include_role:
        name: "../../requirements_roles/infra-ansible/roles/file-management/remove-files"
      vars:
        dry_run: false
        directory: "{{ scm_dir }}/queue"
        files: "user-management-*.json"
        match: "{{ emails_to_match | unique }}"
      when:
        - emails_to_match is defined

    - name: "Capture processed filenames"
      set_fact:
        processed_files: "{{ ( processed_files | default('') ) + ( filepath | basename ) + ',' }}"
      loop_control:
        loop_var: filepath
      with_items:
        - "{{ files_to_remove }}"
      when:
        - files_to_remove is defined
        - files_to_remove != ''

    - name: "Push git repository"
      include_role:
        name: "../../requirements_roles/infra-ansible/roles/scm/git"
      vars:
        action: push
        git_config:
          name: Git Bot
          username: git-bot
          email: git-bot@no-reply
          message: |
            "
            Removed processed files

            The following files were removed from the job queue:
            {% for file in (processed_files.split(',')) %}
            - {{ file }}
            {% endfor %}
            "
          remove_local: false
      when:
        - repository is defined
        - processed_files is defined
        - processed_files != ''

    - name: Pre-populate identities
      set_fact:
        identities: "{{ lodestar_identities }}"
